export const allCars=[
  {
    "image": "https://imgd.aeplcdn.com/227x128/n/cw/ec/123185/grand-vitara-exterior-right-front-three-quarter-2.jpeg?isig=0&q=75",
    "company": "Maruti suzuki",
    "model": "Brezza",
    "prize": "₹ 8.18 Lakh",
    "engine": "1462cc,4 Cylinders Inline,4 Valves/Cylinders,DOHC",
    "engine_type": "K15C smart hybrid",
    "fuel_type": "petrol",
    "max_power": "102bhp@600rpm",
    "max_torque": "136.8Nm@4400rpm", 
    "max_motor_performance": "289",
    "mileage": "20.1",
    "driving_range": "965",
    "drivetrain": "F21D",
    "transmission": "Manual-5 Gears",
    "emission_standard": "BS6",
    "length": "3995",
    "width": "1790",
    "height": "1685",
    "wheelbase": "2500",
    "ground_clearance": "-",
    "doors": "5",
    "seating_capacity": "5",
    "number_of_seating": "2",
    "Bootspace": "328",
    "feul_tank_capacity": "48",
    "front_suspension": "Mac Pherson Strut & coil",
    "rear_suspension": "Torsion Beam & coil spring",
    "front_break_type": "Ventiled Disc",
    "rear_break_type": "Drum",
    "minimum_turning_Radius": "-",
    "stearing_type": "power Assisted",
    "wheels": "steel Rims",
    "sparewheel": "Steel",
    "front_tyres": "215/60R16",
    "rear_tyres": "215/60R16"
  },
  {
    "image": "https://imgd.aeplcdn.com/227x128/n/cw/ec/123185/grand-vitara-exterior-right-front-three-quarter-2.jpeg?isig=0&q=75",
    "company": "Maruti suzuki",
    "model": "Grand-vitara",
    "prize": "₹ 10.45 Lakh",
    "engine": "1462cc,4 Cylinders Inline,4 Valves/Cylinders,DOHC",
    "engine_type": "K15C +Mild Hybrid sysytem",
    "fuel_type": "Mild Hybrid(Electirc+Petrol)",
    "max_power": "102bhp@ 6000 Rpm",
    "max_torque": "136.8 nm@ 4400 rpm",
    "max_motor_performance": "12",
    "mileage": "21.11",
    "driving_range": "950",
    "drivetrain": "FWD",
    "transmission": "Manual-5Gx",
    "emission_standard": "Bs6",
    "length": "4345",
    "width": "1795",
    "height": "1645",
    "wheelbase": "2600",
    "ground_clearance": "210",
    "doors": "5",
    "seating_capacity": "5",
    "number_of_seating": "2",
    "Bootspace": "373",
    "feul_tank_capacity": "45",
    "front_suspension": "Mac Pherson Strut",
    "rear_suspension": "Torsion Beam",
    "front_break_type": "Ventiled Disc",
    "rear_break_type": "Disc",
    "minimum_turning_Radius": "5.4",
    "stearing_type": "power assisted",
    "wheels": "Steel Rims",
    "sparewheel": "Steel",
    "front_tyres": "215/60 R17",
    "rear_tyres": "215/60 R17"
  },
  {
    "image": "https://imgd.aeplcdn.com/227x128/n/cw/ec/54399/exterior-right-front-three-quarter-10.jpeg?q=75",
    "company": "Maruti suzuki",
    "model": "swift",
    "prize": "₹ 5.99 Lakh",
    "engine": "1197 cc ,4 cylinders Inline, 4 Valves/Cylinder, DOHC",
    "engine_type": "1.2L Dual jet",
    "fuel_type": "Petrol",
    "max_power": "89 bhp @ 6000 rpm",
    "max_torque": "114 Nm @ 4400 rpm",
    "max_motor_performance": "39",
    "mileage": "22.38",
    "driving_range": "828",
    "drivetrain": "FWD",
    "transmission": "Manual-5 Gears",
    "emission_standard": "BS 6",
    "length": "3845",
    "width": "1735",
    "height": "1530",
    "wheelbase": "2450",
    "ground_clearance": "-",
    "doors": "5",
    "seating_capacity": "5",
    "number_of_seating": "2",
    "Bootspace": "268",
    "feul_tank_capacity": "37",
    "front_suspension": "MacPherson Strut",
    "rear_suspension": "Torsiion Beam",
    "front_break_type": "Disc",
    "rear_break_type": "Drum",
    "minimum_turning_Radius": "4.8",
    "stearing_type": "power assisterd(Electirc)",
    "wheels": "steel rims",
    "sparewheel": "Steel",
    "front_tyres": "165/80 R14",
    "rear_tyres": "165/80 R14"
  },
  {
    "image": "https://imgd.aeplcdn.com/227x128/n/cw/ec/102663/baleno-exterior-right-front-three-quarter-2.jpeg?isig=0&q=75",
  "company": "Maruti suzuki",
  "model": "Baleno",
  "prize": "₹ 6.56 Lakh",
  "engine": "1197 cc, 4 Cyllinders Inline,4 valves/Cylinder,DOHC",
  "engine_type": "1,2L VVT",
  "fuel_type": "Petrol",
  "max_power": "88bhp @ 6000 rpm",
  "max_torque": "113 Nm@4400 rpm",
  "max_motor_performance": "85.1",
  "mileage": "22.3",
  "driving_range": "827",
  "drivetrain": "FWD",
  "transmission": "Manual -5 Gears",
  "emission_standard": "Bs6",
  "length": "3990",
  "width": "1745",
  "height": "1500",
  "wheelbase": "2520",
  "ground_clearance": "2600",
  "doors": "5",
  "seating_capacity": "5",
  "number_of_seating_rows": "3",
  "Bootspace": "318",
  "feul_tank_capacity": "37",
  "front_suspension": "McPherson Strut",
  "rear_suspension": "Torsion Beam",
  "front_break_type": "Disc",
  "rear_break_type": "Drum",
  "minimum_turning_Radius": "4.9",
  "stearing_type": "Power assisted",
  "wheels": "Steel Rims",
  "sparewheel": "Steel",
  "front_tyres": "185/65 R15",
  "rear_tyres": "185/65 R15"
  },
  {
    "image": "https://imgd.aeplcdn.com/227x128/n/cw/ec/115777/2022-ertiga-exterior-right-front-three-quarter-3.jpeg?isig=0&q=75",
    "company": "Maruti suzuki",
    "model": "Ertiga",
    "prize": "₹ 8.49 Lakh",
    "engine": "1462 cc, 4Cylinders inline,4 Valves/Cylinder, DOHC",
    "engine_type": "K15C Smart Hybrid ",
    "fuel_type": "Petrol",
    "max_power": "102 bhb@ 600 rpm",
    "max_torque": "136.8Nm @ 4400 rpm",
    "max_motor_performance": "20.5",
    "mileage": "20.5",
    "driving_range": "923",
    "drivetrain": "FWD",
      "transmission": "Manual-5 Gears",
      "emission_standard": "BS6",
      "length": "4395",
      "width": "1735",
      "height": "1690",
      "wheelbase": "2740",
      "ground_clearance": "2500",
      "doors": "5",
      "seating_capacity": "7",
      "number_of_seating": "3",
      "Bootspace": "_",
      "feul_tank_capacity": "45",
      "front_suspension": "Mac pherson & coil Spring",
      "rear_suspension": "Torsion Beam & COil Spring",
      "front_break_type": "Disc",
      "rear_break_type": "Drum",
      "minimum_turning_Radius": "5.2",
      "stearing_type": "power Assisted",
      "wheels": "Steel Rims",
      "sparewheel": "Steel",
      "front_tyres":"185/65 R15",
      "rear_tyres": "185/65 R15"
  },
  {
    "image": "https://imgd.aeplcdn.com/227x128/n/cw/ec/41645/tata-nexon-right-front-three-quarter3.jpeg?q=75",
    "company": "Tata",
    "model": "Nexon",
    "prize": "₹ 7.79 Lakh",
    "engine": "1199cc,3Cylinders Inline, 2Vlaves/Cylinder,SOHC",
    "engine_type": "1.2lTurbocharged Revortron",
    "fuel_type": "Petrol",
    "max_power": "118bhp @ 5500 rpm",
    "max_torque": "170 Nm @1750",
    "max_motor_performance": "47",
    "mileage": "17.5",
    "driving_range": "773",
    "drivetrain": "FWD",
    "transmission": "Manul-6Gears, Sport Mode",
    "emission_standard": "BS6",
    "length": "3993",
    "width": "1811",
    "height": "1606",
    "wheelbase": "2498",
    "ground_clearance": "209",
    "doors": "5",
    "seating_capacity": "5",
    "number_of_seating": "2",
    "Bootspace": "350",
    "feul_tank_capacity": "44",
    "front_suspension": "Semi-Independent; closed profile Twist beam with coil",
    "rear_suspension": "Independent.Lower Wishbone",
    "front_break_type": "Disc",
    "rear_break_type": "Drum",
    "minimum_turning_Radius": "5.1",
    "stearing_type": "Power Assited(Electric)",
    "wheels": "Steel Rims",
    "sparewheel": "Steel",
    "front_tyres": "195/60 R16",
    "rear_tyres": "195/60 R16"
  },
  {
    "image": "https://imgd.aeplcdn.com/227x128/n/cw/ec/39015/punch-exterior-right-front-three-quarter-2.jpeg?isig=0&q=75",
    "company": "Tata",
    "model": "Punch",
    "prize": "₹ 6.00 Lakh",
    "engine": "1199CC,3Cylinders Inline 4Valves/Cylinder,SOHC",
    "engine_type": "1.2Revortron",
    "fuel_type": "Petrol",
    "max_power": "84bhp @ 6000rpm",
    "max_torque": "113 Nm @ 3300 rpm",
    "max_motor_performance": "22",
    "mileage": "18.9",
    "driving_range": "702",
    "drivetrain": "1FWD",
    "transmission": "Manual-5 gears",
    "emission_standard": "BS 6",
    "length": "3827",
    "width": "1742",
    "height": "1615",
    "wheelbase": "2445",
    "ground_clearance": "187",
    "doors": "5",
    "seating_capacity": "5",
    "number_of_seating": "2",
    "Bootspace": "366",
    "feul_tank_capacity": "37",
    "front_suspension": "Independent, Lower Wishbone Mcpherson Strut with Coil spring",
    "rear_suspension": "semi-independent Twist BEAM WITH COIL SPRING andshock absorber",
    "front_break_type": "Disc",
    "rear_break_type": "Drum",
    "minimum_turning_Radius": "-",
    "stearing_type": "power assisted(electirc)",
    "wheels": "Steel RIMS",
    "sparewheel": "Steel",
    "front_tyres": "185/70R15",
    "rear_tyres": "185/70R15"
  },
  {
    "image": "https://imgd.aeplcdn.com/227x128/n/cw/ec/142739/harrier-exterior-right-front-three-quarter-2.jpeg?isig=0&q=75",
    "company": "Tata",
    "model": "Harrier",
    "prize": "₹ 15.00 Lakh",
    "engine": "1956 cc,4 Cylinders Inline,4Vlves/Cylinder,DOHC",
    "engine_type": "2.0 L Kryotec",
    "fuel_type": "Diesel",
    "max_power": "168 bhp @ 3750 rpm",
    "max_torque": "113 Nm@ 3300",
    "max_motor_performance": "67",
    "mileage": "18.5",
    "driving_range": "684",
    "drivetrain": "FWD",
    "transmission": "Manual-5  Gears",
    "emission_standard": "BS 6",
    "length": "3990",
    "width": "1894",
    "height": "1706",
    "wheelbase": "2741",
    "ground_clearance": "205",
    "doors": "5",
    "seating_capacity": "5",
    "number_of_seating": "2",
    "Bootspace": "425",
    "feul_tank_capacity": "50",
    "front_suspension": "Independent, Lower Wishbone, McPherson Strut with Coil Spring & Anti Roll Bar",
    "rear_suspension": "Semi Independent Twist Blade with Panhard Rod and Coil Spring",
    "front_break_type": "Disc",
    "rear_break_type": "Drum",
    "minimum_turning_Radius": "5.75",
    "stearing_type": "Power assisted (Hydraulic)",
    "wheels": "Alloy Wheels",
    "sparewheel": "Steel",
    "front_tyres": "235 / 65 R17",
    "rear_tyres": "235 / 65 R18"
  },
  {
    "image": "https://imgd.aeplcdn.com/227x128/n/cw/ec/32597/altroz-exterior-right-front-three-quarter-79.jpeg?isig=0&q=75",
    "company": "Tata",
    "model": "Altroz",
    "prize": "₹ 6.44 Lakh",
    "engine": "1199 cc, 3 Cylinders Inline, 4 Valves/Cylinder, DOHC",
    "engine_type": "1.2 L Revotron",
    "fuel_type": "Petrol",
    "max_power": "85 bhp @ 6000 rpm",
    "max_torque": "113 Nm @ 3300 rpm",
    "max_motor_performance": "199",
    "mileage": "18.5",
    "driving_range": "684",
    "drivetrain": "FWD",
    "transmission": "Manual - 5 Gears",
    "emission_standard": "BS 6",
    "length": "3990",
    "width": "31755",
    "height": "1523",
    "wheelbase": "2501",
    "ground_clearance": "165",
    "doors": "5",
    "seating_capacity": "5",
    "number_of_seating": "2",
    "Bootspace": "2345",
    "feul_tank_capacity": "37",
    "front_suspension": "Independent MacPherson dual path strut with coil spring",
    "rear_suspension": "Twist beam with coil spring and shock absorber",
    "front_break_type": "Disc",
    "rear_break_type": "Drum",
    "minimum_turning_Radius": "5",
    "stearing_type": "Power assisted (Electric)",
    "wheels": "Steel Rims",
    "sparewheel": "Steel",
    "front_tyres": "165 / 80 R14",
    "rear_tyres": "165 / 80 R14"
  },
  {
    "image": "https://imgd.aeplcdn.com/227x128/n/cw/ec/142865/safari-exterior-right-front-three-quarter-2.jpeg?isig=0&q=75",
    "company": "Tata",
    "model": "safari",
    "prize": "₹ 15.65 Lakh",
    "engine": "1956 cc, 4 Cylinders Inline, 4 Valves/Cylinder, DOHC",
    "engine_type": "2.0 L Kryotec",
    "fuel_type": "Diesel",
    "max_power": "168 bhp @ 3750 rpm",
    "max_torque": "350 Nm @ 1750 rpm",
    "max_motor_performance": "29",
    "mileage": "16.14",
    "driving_range": "807",
    "drivetrain": "FWD",
    "transmission": "Manual - 6 Gears",
    "emission_standard": "BS6 Phase 2",
    "length": "4661",
    "width": "1894",
    "height": "1786",
    "wheelbase": "2741",
    "ground_clearance": "205",
    "doors": "5",
    "seating_capacity": "7",
    "number_of_seating": "3",
    "Bootspace": "447",
    "feul_tank_capacity": "Independent, Lower Wishbone, McPherson Strut with Coil Spring & Anti Roll Bar",
    "front_suspension": "Semi Independent Twist Blade with Panhard Rod and Coil Spring",
    "rear_suspension": "Disc",
    "front_break_type": "Disc",
    "rear_break_type": "11.6",
    "minimum_turning_Radius": "11.6",
    "stearing_type": "Power assisted (Hydraulic)",
    "wheels": "Steel Rims",
    "sparewheel": "Steel",
    "front_tyres": "235/70 R16",
    "rear_tyres": "235/70 R16"
  },
  {
    "image": "https://imgd.aeplcdn.com/227x128/n/cw/ec/115025/innova-hycross-exterior-right-front-three-quarter-2.jpeg?isig=0&q=75",
    "company": "Toyota",
    "model": "Innova Hycross",
    "prize": "₹ 18.55 Lakh",
    "engine": "1987 cc, 4 Cylinders Inline, 4 Valves/Cylinder, DOHC",
    "engine_type": "TNGA",
    "fuel_type": "Petrol",
    "max_power": "173 bhp @ 6600 rpm",
    "max_torque": "209 Nm @ 4500 rpm",
    "max_motor_performance": "209 Nm @ 4500 rpm",
    "mileage": "6.13",
    "driving_range": "839",
    "drivetrain": "FWD",
    "transmission": "Automatic (CVT) - CVT Gears, Manual Override",
    "emission_standard": "BS 6",
    "length": "4755",
    "width": "1845",
    "height": "1785",
    "wheelbase": "2850",
    "ground_clearance": "-",
    "doors": "5",
    "seating_capacity": "7",
    "number_of_seating": "3",
    "Bootspace": "-",
    "feul_tank_capacity": "52",
    "front_suspension": "MacPherson Strut",
    "rear_suspension": "Semi-independent Torsion beam",
    "front_break_type": "Disc",
    "rear_break_type": "Disc",
    "minimum_turning_Radius": "-",
    "stearing_type": "Power assisted (Electric)",
    "wheels": "Steel Rims",
    "sparewheel": "Steel",
    "front_tyres": "205 / 65 R16",
    "rear_tyres": "205 / 65 R16"
  },
  {
    "image": "https://imgd.aeplcdn.com/227x128/n/cw/ec/44709/fortuner-exterior-right-front-three-quarter-19.jpeg?q=75",
    "company": "Toyota",
    "model": "Fortuner",
    "prize": "₹ 32.58 Lakh",
    "engine": "2694 cc, 4 Cylinders Inline, 4 Valves/Cylinder, DOHC",
    "engine_type": "2TR-FE I4 Dual VVT-i",
    "fuel_type": "Petrol",
    "max_power": "164 bhp @ 5200 rpm",
    "max_torque": "245 Nm @ 4000 rpm",
    "max_motor_performance": "219",
    "mileage": "10",
    "driving_range": "800",
    "drivetrain": "RWD",
    "transmission": "Manual - 5 Gears, Sport Mode",
    "emission_standard": "BS 6",
    "length": "4795",
    "width": "1855",
    "height": "1835",
    "wheelbase": "2745",
    "ground_clearance": "-",
    "doors": "5",
    "seating_capacity": "7",
    "number_of_seating": "3",
    "Bootspace": "296",
    "feul_tank_capacity": "80",
    "front_suspension": "Double Wishbone with Stabiliser",
    "rear_suspension": "4-Link with Coil Spring and Stabiliser",
    "front_break_type": "Ventilated Disc",
    "rear_break_type": "Ventilated Disc",
    "minimum_turning_Radius": "5.8",
    "stearing_type": "Power assisted (Hydraulic)",
    "wheels": "Alooy Wheels",
    "sparewheel": "Alloy",
    "front_tyres": "265 / 65 R17",
    "rear_tyres": "265 / 65 R17"
  },
  {
    "image": "https://imgd.aeplcdn.com/227x128/n/cw/ec/112839/glanza-facelift-exterior-right-front-three-quarter.jpeg?isig=0&q=75",
    "company": "Toyato",
    "model": "Glanza",
    "prize": "₹ 6.16 Lakh",
    "engine": "1197 cc, 4 Cylinders Inline, 4 Valves/Cylinder, DOHC",
    "engine_type": "1.2L VVT",
    "fuel_type": "petrol",
    "max_power": "88 bhp @ 6000 rpm",
    "max_torque": "113 Nm @ 4400 rpm",
    "max_motor_performance": "156",
    "mileage": "22.3",
    "driving_range": "827",
    "drivetrain": "FWD",
    "transmission": "Manual - 5 Gears",
    "emission_standard": "BS 6",
    "length": "3990",
    "width": "1745",
    "height": "1500",
    "wheelbase": "2520",
    "ground_clearance": "-",
    "doors": "5",
    "seating_capacity": "7",
    "number_of_seating": "2",
    "Bootspace": "318",
    "feul_tank_capacity": "37",
    "front_suspension": "MacPherson Strut",
    "rear_suspension": "Torsion Beam",
    "front_break_type": "Disc",
    "rear_break_type": "Drum",
    "minimum_turning_Radius": "4.9",
    "stearing_type": "Power assisted (Electric)",
    "wheels": "Steel Rims",
    "sparewheel": "steel",
    "front_tyres": "185 / 65 R15",
    "rear_tyres": "185 / 65 R15"
  },
  {
    "image": "https://imgd.aeplcdn.com/227x128/n/cw/ec/47016/urban-cruiser-exterior-right-front-three-quarter-61.jpeg?isig=0&q=75",
    "company": "Toyota",
    "model": "Urban cruiser",
    "prize": "₹ 11.02 Lakh",
    "engine": "1462 cc, 4 Cylinders Inline, 4 Valves/Cylinder, DOHC",
    "engine_type": "K15B ISG",
    "fuel_type": "Petrol",
    "max_power": "103 bhp @ 6000 rpm",
    "max_torque": "138 Nm @ 4400 rpm",
    "max_motor_performance": "130",
    "mileage": "18.7",
    "driving_range": "900",
    "drivetrain": "FWD",
    "transmission": "Automatic (TC) - 4 Gears",
    "emission_standard": "BS 6",
    "length": "3995",
    "width": "1790",
    "height": "1640",
    "wheelbase": "2500",
    "ground_clearance": "8",
    "doors": "5",
    "seating_capacity": "5",
    "number_of_seating": "2",
    "Bootspace": "328",
    "feul_tank_capacity": "48",
    "front_suspension": "McPherson Strut with Coil Spring",
    "rear_suspension": "Torsion Beam with Coil Spring",
    "front_break_type": "Ventilated Disc",
    "rear_break_type": "Drum",
    "minimum_turning_Radius": "5.2",
    "stearing_type": "Power assisted (Electric)",
    "wheels": "Alloy Wheels",
    "sparewheel": "Steel",
    "front_tyres": "215 / 60 R16",
    "rear_tyres": "215 / 60 R16"
  },
  {
    "image": "https://imgd.aeplcdn.com/227x128/n/cw/ec/139739/land-cruiser-exterior-right-front-three-quarter.jpeg?isig=0&q=75",
    "company": "Toyota",
    "model": "Land cruiser",
    "prize": "₹ 2.10 Crore",
    "engine": "3346 cc, 6 Cylinders In V Shape, 4 Valves/Cylinder, DOHC",
    "engine_type": "V6 3.3L Turbo",
    "fuel_type": "Diesel",
    "max_power": "304 bhp @ 4000 rpm",
    "max_torque": "700 Nm @ 1600 rpm",
    "max_motor_performance": "16",
    "mileage": "-",
    "driving_range": "-",
    "drivetrain": "AWD",
    "transmission": "Automatic - 6 Gears, Manual Override, Sport Mode",
    "emission_standard": "BS 6",
    "length": "4985",
    "width": "1980",
    "height": "1945",
    "wheelbase": "2850",
    "ground_clearance": "-",
    "doors": "5",
    "seating_capacity": "5",
    "number_of_seating": "2",
    "Bootspace": "-",
    "feul_tank_capacity": "110",
    "front_suspension": "Double Wishbone Independent;",
    "rear_suspension": "4-Link Rigid",
    "front_break_type": "Disc",
    "rear_break_type": "Disc",
    "minimum_turning_Radius": "-",
    "stearing_type": "Power assisted (Hydraulic)",
    "wheels": "Alloy Wheels",
    "sparewheel": "Alloy",
    "front_tyres": "265 / 55 R20",
    "rear_tyres": "265 / 55 R20"
  },
  {
    "image": "https://imgd.aeplcdn.com/227x128/n/cw/ec/140591/new-x1-exterior-right-front-three-quarter-2.jpeg?isig=0&q=75",
    "company": "BMW",
    "model": "BMW X1",
    "prize": "₹ 45.90 Lakh",
    "engine": "1499 cc, 3 Cylinders Inline, 4 Valves/Cylinder, DOHC",
    "engine_type": "TwinPower Turbo 3-Cylinder engine",
    "fuel_type": "Petrol",
    "max_power": "134 bhp @ 4400 rpm",
    "max_torque": "230 Nm @ 1500 rpm",
    "max_motor_performance": "223",
    "mileage": "16.3",
    "driving_range": "831",
    "drivetrain": "FWD",
    "transmission": "Automatic (DCT) - 7 Gears, Manual Override & Paddle Shift, Sport Mode",
    "emission_standard": "BS 6",
    "length": "4500",
    "width": "1845",
    "height": "1630",
    "wheelbase": "2692",
    "ground_clearance": "183",
    "doors": "5",
    "seating_capacity": "5",
    "number_of_seating": "2",
    "Bootspace": "476",
    "feul_tank_capacity": "476",
    "front_suspension": "Single-joint Spring-strut Axle",
    "rear_suspension": "Multi-arm Axle with Separate Spring and Damper",
    "front_break_type": "Ventilated Disc",
    "rear_break_type": "Ventilated Disc",
    "minimum_turning_Radius": "5.8",
    "stearing_type": "Power assisted (Electric)",
    "wheels": "Alloy Wheels",
    "sparewheel": "Space Saver",
    "front_tyres": "225 / 55 R18",
    "rear_tyres": "225 / 55 R18"
  },
  {
    "image": "https://imgd.aeplcdn.com/227x128/cw/ec/37067/BMW-3-Series-Exterior-167583.jpg?wm=0&q=75",
    "company": "BMW",
    "model": "BMW 3 Series",
    "prize": "₹ 46.86 Lakh",
    "engine": "1998 cc, 4 Cylinders Inline, 4 Valves/Cylinder, DOHC",
    "engine_type": "B48 Turbocharged I4",
    "fuel_type": "PETROL",
    "max_power": "255 bhp @ 5000 rpm",
    "max_torque": "400 Nm @ 1550 rpm",
    "max_motor_performance": "138",
    "mileage": "16.1",
    "driving_range": "951.67",
    "drivetrain": "RWD",
    "transmission": "Automatic (TC) - 8 Gears, Manual Override & Paddle Shift, Sport Mode	",
    "emission_standard": "BS 6",
    "length": "4709",
    "width": "1827",
    "height": "1435",
    "wheelbase": "2851",
    "ground_clearance": "135",
    "doors": "4",
    "seating_capacity": "5",
    "number_of_seating": "2",
    "Bootspace": "480",
    "feul_tank_capacity": "59",
    "front_suspension": "Double-joint spring strut axle, hydraulically damped torque strut bearing",
    "rear_suspension": "Five-link axle",
    "front_break_type": "Ventilated Disc",
    "rear_break_type": "Ventilated Disc",
    "minimum_turning_Radius": "6",
    "stearing_type": "Power assisted (Electric)",
    "wheels": "Alloy Wheels",
    "sparewheel": "Space Saver",
    "front_tyres": "225 / 50 R17",
    "rear_tyres": "225 / 50 R17"
  },
  {
    "image": "https://imgd.aeplcdn.com/227x128/cw/ec/37095/BMW-Z4-Roadster-Right-Front-Three-Quarter-153914.jpg?wm=0&q=75",
    "company": "BMW",
    "model": "BMW Z4",
    "prize": "₹ 71.82 Lakh",
    "engine": "1998 cc, 4 Cylinders Inline, 4 Valves/Cylinder, DOHC",
    "engine_type": "B48 Turbocharged I4",
    "fuel_type": "Petrol",
    "max_power": "194 bhp @ 4500 rpm",
    "max_torque": "320 Nm @ 1450 rpm",
    "max_motor_performance": "164",
    "mileage": "14.3",
    "driving_range": "747",
    "drivetrain": "RWD",
    "transmission": "Automatic (TC) - 8 Gears, Manual Override & Paddle Shift, Sport Mode",
    "emission_standard": "BS 6",
    "length": "4324",
    "width": "1864",
    "height": "1304",
    "wheelbase": "2470",
    "ground_clearance": "117",
    "doors": "2",
    "seating_capacity": "2",
    "number_of_seating": "1",
    "Bootspace": "281",
    "feul_tank_capacity": "52",
    "front_suspension": "Double-joint Spring-strut Axle",
    "rear_suspension": "Five-link Axle",
    "front_break_type": "Ventilated Disc",
    "rear_break_type": "Ventilated Disc",
    "minimum_turning_Radius": "5.5",
    "stearing_type": "Power assisted (Electric)",
    "wheels": "Alloy Wheels",
    "sparewheel": "X",
    "front_tyres": "225 / 50 R17",
    "rear_tyres": "255 / 45 R17"
  },
  {
    "image": "https://imgd.aeplcdn.com/227x128/n/cw/ec/139177/3-series-gran-limousine-exterior-right-front-three-quarter-2.jpeg?isig=0&q=75",
    "company": "BMW",
    "model": "BMW 3 Series Gran Limousine",
    "prize": "₹ 56.84 Lakh",
    "engine": "1998 cc, 4 Cylinders Inline, 4 Valves/Cylinder, DOHC",
    "engine_type": "B48 Turbocharged I4",
    "fuel_type": "Petrol",
    "max_power": "255 bhp @ 5000 rpm",
    "max_torque": "400 Nm @ 1550 rpm",
    "max_motor_performance": "22",
    "mileage": "15.39",
    "driving_range": "908",
    "drivetrain": "RWD",
    "transmission": "Automatic (TC) - 8 Gears, Manual Override & Paddle Shift, Sport Mode",
    "emission_standard": "BS 6",
    "length": "4819",
    "width": "1827",
    "height": "1441",
    "wheelbase": "2961",
    "ground_clearance": "135",
    "doors": "4",
    "seating_capacity": "5",
    "number_of_seating": "2",
    "Bootspace": "480",
    "feul_tank_capacity": "59",
    "front_suspension": "Double-joint spring-strut axle in lightweight aluminium-steel construction, hydraulically damped torque strut bearingsconstruction",
    "rear_suspension": "Five-link axle in lightweight aluminium-steel construction",
    "front_break_type": "Ventilated Disc",
    "rear_break_type": "Ventilated Disc",
    "minimum_turning_Radius": "6",
    "stearing_type": "Power assisted (Electric)",
    "wheels": "Alloy Wheels",
    "sparewheel": "Space Saver",
    "front_tyres": "225 / 45 R18",
    "rear_tyres": "255 / 40 R18"
  },
  {
    "image": "https://imgd.aeplcdn.com/227x128/n/cw/ec/96443/5-series-exterior-right-front-three-quarter-4.jpeg?q=75",
    "company": "BMW",
    "model": "BMW 5 Series",
    "prize": "₹ 64.49 Lakh",
    "engine": "1998 cc, 4 Cylinders Inline, 4 Valves/Cylinder, DOHC",
    "engine_type": "2.0L B48 Turbocharged I4",
    "fuel_type": "Petrol",
    "max_power": "252 bhp @ 5200 rpm",
    "max_torque": "350 Nm @ 1450 rpm",
    "max_motor_performance": "29",
    "mileage": "14.8",
    "driving_range": "1008",
    "drivetrain": "RWD",
    "transmission": "Automatic (TC) - 8 Gears, Manual Override & Paddle Shift, Sport Mode",
    "emission_standard": "BS 6",
    "length": "4953",
    "width": "1868",
    "height": "1467",
    "wheelbase": "2975",
    "ground_clearance": "-",
    "doors": "4",
    "seating_capacity": "5",
    "number_of_seating": "2",
    "Bootspace": "530",
    "feul_tank_capacity": "68",
    "front_suspension": "Double Track Control Arm Axle",
    "rear_suspension": "Five-link Axle",
    "front_break_type": "Ventilated Disc",
    "rear_break_type": "Ventilated Disc",
    "minimum_turning_Radius": "6.03",
    "stearing_type": "Power assisted (Electric)",
    "wheels": "Alloy Wheels",
    "sparewheel": "Space Saver",
    "front_tyres": "245 / 45 R18",
    "rear_tyres": "275 / 40 R18"
  },
  {
    "image": "https://imgd.aeplcdn.com/227x128/n/cw/ec/40087/thar-exterior-right-front-three-quarter-11.jpeg?q=75",
    "company": "Mahindra",
    "model": "Mahindra Thar",
    "prize": "₹ 9.99 Lakh",
    "engine": "1497 cc, 4 Cylinders Inline, 4 Valves/Cylinder, DOHC",
    "engine_type": "D117 CRDe",
    "fuel_type": "Diesel",
    "max_power": "117 bhp @ 3500 rpm",
    "max_torque": "300 Nm @ 1750 rpm",
    "max_motor_performance": "174",
    "mileage": "-",
    "driving_range": "-",
    "drivetrain": "RWD",
    "transmission": "Manual - 6 Gears",
    "emission_standard": "BS 6",
    "length": "3985",
    "width": "1820",
    "height": "1844",
    "wheelbase": "2450",
    "ground_clearance": "226",
    "doors": "3",
    "seating_capacity": "4",
    "number_of_seating": "2",
    "Bootspace": "-",
    "feul_tank_capacity": "45",
    "front_suspension": "Independent Double Wishbone with Coil Over Damper & Stabiliser Bar",
    "rear_suspension": "Multilink solid Rear Axle with Coil spring & Stabiliser Bar",
    "front_break_type": "Disc",
    "rear_break_type": "Drum",
    "minimum_turning_Radius": "-",
    "stearing_type": "Power assisted (Hydraulic)",
    "wheels": "Steel Rims",
    "sparewheel": "Steel",
    "front_tyres": "245 / 75 R16",
    "rear_tyres": "245 / 75 R16"
  },
  {
    "image": "https://imgd.aeplcdn.com/227x128/n/cw/ec/128413/scorpio-exterior-right-front-three-quarter-46.jpeg?isig=0&q=75",
    "company": "Mahindra",
    "model": "Mahindra Scorpio",
    "prize": "₹ 12.64 Lakh",
    "engine": "2184 cc, 4 Cylinders Inline, 4 Valves/Cylinder, DOHC",
    "engine_type": "2.2 L mHawk",
    "fuel_type": "Diesel",
    "max_power": "130 bhp @ 3750 rpm",
    "max_torque": "300 Nm @ 1600 rpm",
    "max_motor_performance": "15",
    "mileage": "15",
    "driving_range": "900",
    "drivetrain": "RWD",
    "transmission": "Manual - 6 Gears",
    "emission_standard": "BS 6",
    "length": "4456",
    "width": "1820",
    "height": "1995",
    "wheelbase": "2680",
    "ground_clearance": "209",
    "doors": "5",
    "seating_capacity": "7",
    "number_of_seating": "3",
    "Bootspace": "-",
    "feul_tank_capacity": "60",
    "front_suspension": "Double Wish-bone Type, Independent Front Coil Spring",
    "rear_suspension": "Mulit-link Coil Spring Suspension with Anti-Roll Bar",
    "front_break_type": "Disc",
    "rear_break_type": "Drum",
    "minimum_turning_Radius": "5.4",
    "stearing_type": "Power assisted (Hydraulic)",
    "wheels": "Steel Rims",
    "sparewheel": "Steel",
    "front_tyres": "235 / 65 R17",
    "rear_tyres": "235 / 65 R17"
  },
  {
     "image": "https://imgd.aeplcdn.com/227x128/n/cw/ec/42355/xuv700-exterior-right-front-three-quarter.jpeg?isig=0&q=75",
  "company": "Mahindra",
  "model": "Mahindra XUV700",
  "prize": "₹ 13.95 Lakh",
  "engine": "1997 cc, 4 Cylinders Inline, 4 Valves/Cylinder, DOHC",
  "engine_type": "2.0 Turbo Petrol With Direct Injection",
  "fuel_type": "Petrol",
  "max_power": "197 bhp @ 5000 rpm",
  "max_torque": "380 Nm @ 1750 rpm",
  "max_motor_performance": "198.212.126",
  "mileage": "243",
  "driving_range": "219",
  "drivetrain": "FWD",
  "transmission": "Manual - 6 Gears",
  "emission_standard": "BS 6",
  "length": "4695",
  "width": "1890",
  "height": "1755",
  "wheelbase": "2750",
  "ground_clearance": "-",
  "doors": "5",
  "seating_capacity": "5",
  "number_of_seating": "2",
  "Bootspace": "-",
  "feul_tank_capacity": "60",
  "front_suspension": "McPherson Strut Independent Suspension with FSD and Stabilizer bar",
  "rear_suspension": "Multi-link Independent Suspension with FSD and Stabilizer bar",
  "front_break_type": "Ventilated Disc",
  "rear_break_type": "Disc",
  "minimum_turning_Radius": "-",
  "stearing_type": "Power assisted",
  "wheels": "Steel Rims",
  "sparewheel": "Space Saver",
  "front_tyres": "235 / 65 R17",
  "rear_tyres": "235 / 65 R17"
  },
  {
    "image": "https://imgd.aeplcdn.com/227x128/n/cw/ec/40432/scorpio-n-exterior-right-front-three-quarter-15.jpeg?isig=0&q=75",
    "company": "Mahindra",
    "model": "Mahindra Scorpio N",
    "prize": "₹ 12.74 Lakh",
    "engine": "1997 cc, 4 Cylinders Inline, 4 Valves/Cylinder, DOHC",
    "engine_type": "2.0L I4 mStallion 150 TGDi",
    "fuel_type": "Petrol",
    "max_power": "200 bhp @ 5000 rpm",
    "max_torque": "370 Nm @ 1750 rpm",
    "max_motor_performance": "137",
    "mileage": "-",
    "driving_range": "-",
    "drivetrain": "RWD",
    "transmission": "Manual - 6 Gears",
    "emission_standard": "BS 6",
    "length": "4662",
    "width": "1917",
    "height": "1857",
    "wheelbase": "2750",
    "ground_clearance": "187",
    "doors": "5",
    "seating_capacity": "7",
    "number_of_seating": "3",
    "Bootspace": "-",
    "feul_tank_capacity": "57",
    "front_suspension": "Front Suspension: Double Wishbone Suspension with Coil over Shocks with FDD & MTV-CL",
    "rear_suspension": "Rear Suspension: Pentalink Suspension with WATT’s Linkage with FDD & MTV-CL",
    "front_break_type": "Ventilated Disc",
    "rear_break_type": "Ventilated Disc",
    "minimum_turning_Radius": "-",
    "stearing_type": "Power assisted (Electric)",
    "wheels": "Steel Rims",
    "sparewheel": "Steel",
    "front_tyres": "245 / 65 R17",
    "rear_tyres": "245 / 65 R17"
  },
  {
    "image": "https://imgd.aeplcdn.com/227x128/n/cw/ec/26918/xuv300-exterior-right-front-three-quarter-148706.jpeg?q=75",
  "company": "Mahidra",
  "model": "Mahindra XUV300",
  "prize": "₹ 8.41 Lakh",
  "engine": "1197 cc, 3 Cylinders Inline, 4 Valves/Cylinder, DOHC",
  "engine_type": "1.2 Turbo Petrol",
  "fuel_type": "Petrol",
  "max_power": "109 bhp @ 5000 rpm",
  "max_torque": "200 Nm @ 2000 rpm",
  "max_motor_performance": "140.69",
  "mileage": "17",
  "driving_range": "714",
  "drivetrain": "FWD",
  "transmission": "Manual - 6 Gears",
  "emission_standard": "BS 6",
  "length": "3995",
  "width": "1821",
  "height": "1627",
  "wheelbase": "2600",
  "ground_clearance": "180",
  "doors": "5",
  "seating_capacity": "5",
  "number_of_seating": "2",
  "Bootspace": "257",
  "feul_tank_capacity": "42",
  "front_suspension": "MacPherson Strut with anti-roll bar",
  "rear_suspension": "Twist beam suspension with coil spring",
  "front_break_type": "Disc",
  "rear_break_type": "Disc",
  "minimum_turning_Radius": "5.3",
  "stearing_type": "Power assisted",
  "wheels": "Steel Rims",
  "sparewheel": "Steel",
  "front_tyres": "205 / 65 R16",
  "rear_tyres": "205 / 65 R16"
  },
  {
    "image": "https://imgd.aeplcdn.com/227x128/n/cw/ec/121943/new-verna-exterior-left-front-three-quarter-2.jpeg?isig=0&q=75",
    "company": "Hyundai",
    "model": "Hyundai New Verna",
    "prize": "₹ 9.63 Lakh",
    "engine": "1497 cc, 4 Cylinders Inline, 4 Valves/Cylinder, DOHC",
    "engine_type": "1.5 l MPi",
    "fuel_type": "Petrol",
    "max_power": "113 bhp @ 6300 rpm",
    "max_torque": "144 Nm @ 4500 rpm",
    "max_motor_performance": "103.242.209",
    "mileage": "17.7",
    "driving_range": "796",
    "drivetrain": "FWD",
    "transmission": "Manual - 6 Gears",
    "emission_standard": "BS 6",
    "length": "4440",
    "width": "1729",
    "height": "1475",
    "wheelbase": "2600",
    "ground_clearance": "	165",
    "doors": "4",
    "seating_capacity": "5",
    "number_of_seating": "2",
    "Bootspace": "480",
    "feul_tank_capacity": "45",
    "front_suspension": "McPherson Strut with Coil Spring",
    "rear_suspension": "Couple Torsion Beam Axle",
    "front_break_type": "Disc",
    "rear_break_type": "Drum",
    "minimum_turning_Radius": "5.2",
    "stearing_type": "Power assisted",
    "wheels": "Steel Rims",
    "sparewheel": "Steel",
    "front_tyres": "185 / 65 R15",
    "rear_tyres": "185 / 65 R15"
  },
  {
    "image": "https://imgd.aeplcdn.com/227x128/n/cw/ec/141121/venue-exterior-right-front-three-quarter.jpeg?isig=0&q=75",
  "company": "Hyundai",
  "model": "Hyundai Venue",
  "prize": "₹ 7.68 Lakh",
  "engine": "1197 cc, 4 Cylinders Inline, 4 Valves/Cylinder, DOHC",
  "engine_type": "1.2 Kappa",
  "fuel_type": "Petrol",
  "max_power": "82 bhp @ 6000 rpm",
  "max_torque": "114 Nm @ 4000 rpm",
  "max_motor_performance": "565.54",
  "mileage": "17.5",
  "driving_range": "789",
  "drivetrain": "FWD",
  "transmission": "Manual - 5 Gears",
  "emission_standard": "BS6 Phase 2",
  "length": "3995",
  "width": "1770",
  "height": "1617",
  "wheelbase": "2500",
  "ground_clearance": "195",
  "doors": "5",
  "seating_capacity": "5",
  "number_of_seating": "2",
  "Bootspace": "350",
  "feul_tank_capacity": "45",
  "front_suspension": "McPherson Strut with Coil Spring",
  "rear_suspension": "Coupled Torsion Beam Axle with Coil Spring",
  "front_break_type": "Disc",
  "rear_break_type": "Drum",
  "minimum_turning_Radius": "-",
  "stearing_type": "Power assisted",
  "wheels": "Steel Rims",
  "sparewheel": "Steel",
  "front_tyres": "195 / 65 R15",
  "rear_tyres": "195 / 65 R15"
  },
  {
    "image": "https://imgd.aeplcdn.com/227x128/n/cw/ec/141115/creta-exterior-right-front-three-quarter.jpeg?isig=0&q=75",
  "company": "Hyundai",
  "model": "Hyundai Creta",
  "prize": "₹ 10.84 Lakh",
  "engine": "1497 cc,4 Cyilnders Inline,4 Valves/Cyilnde,DOHC",
  "engine_type": "1.5| MPi Petro",
  "fuel_type": "Petrol",
  "max_power": "113 bhp @ 6300 rpm",
  "max_torque": "114 Nm @ 4500 rpm",
  "max_motor_performance": "103.235",
  "mileage": "-",
  "driving_range": "-",
  "drivetrain": "FWD",
  "transmission": "Manual-6 Gears",
  "emission_standard": "Bs6 Phase 2",
  "length": "4300",
  "width": "1790",
  "height": "1635",
  "wheelbase": "2610",
  "ground_clearance": "-",
  "doors": "5",
  "seating_capacity": "5",
  "number_of_seating": "2",
  "Bootspace": "443",
  "feul_tank_capacity": "50",
  "front_suspension": "Mc Pherson Strut with Coil Spring",
  "rear_suspension": "Coupled Torison Beam Axle",
  "front_break_type": "Disc",
  "rear_break_type": "Drum",
  "minimum_turning_Radius": "-",
  "stearing_type": "Power assisted",
  "wheels": "Steel Rims",
  "sparewheel": "Steel",
  "front_tyres": "205 / 65 R16",
  "rear_tyres": "205 / 65 R16"
  },
  {
    "image": "https://imgd.aeplcdn.com/227x128/n/cw/ec/136183/grand-i10-nios-facelift-exterior-right-front-three-quarter-2.jpeg?isig=0&q=75",
  "company": "Hyundai",
  "model": "Hyndai Grand i10 Nios",
  "prize": "₹ 5.69 Lakh",
  "engine": "1197 cc,Cyilders Inline,4 Valves/Cylinder,DOHC",
  "engine_type": "1.2 Keppa",
  "fuel_type": "Petrol",
  "max_power": "82 Bhp @ 6000 rpm",
  "max_torque": "114 Nm @ 4000rpm",
  "max_motor_performance": "50",
  "mileage": "21",
  "driving_range": "777",
  "drivetrain": "FWD",
  "transmission": "Manual -5 Gears",
  "emission_standard": "Bs 6",
  "length": "3805",
  "width": "1680",
  "height": "1520",
  "wheelbase": "2450",
  "ground_clearance": "-",
  "doors": "5",
  "seating_capacity": "5",
  "number_of_seating": "2",
  "Bootspace": "260",
  "feul_tank_capacity": "37",
  "front_suspension": "McPherson Strut",
  "rear_suspension": "Coupled Torsion Beam Axle",
  "front_break_type": "Disc",
  "rear_break_type": "Drum",
  "minimum_turning_Radius": "-",
  "stearing_type": "Power assisted",
  "wheels": "Alloy Wheels",
  "sparewheel": "Steel",
  "front_tyres": "175/60 R15",
  "rear_tyres": "175/60 R15"
  },
  {
    "image": "https://imgd.aeplcdn.com/227x128/n/cw/ec/41197/hyundai-verna-right-front-three-quarter7.jpeg?q=75",
  "company": "Hyundai",
  "model": "Hyundai Verna",
  "prize": "₹ 9.63 Lakh",
  "engine": "Cylinders Inline, DOHC",
  "engine_type": "1.5 | MPI",
  "fuel_type": "Petrol",
  "max_power": "113 bhp @6300 rpm",
  "max_torque": "114 Nm @4500 rpm",
  "max_motor_performance": "167.17",
  "mileage": "17.7",
  "driving_range": "796",
  "drivetrain": "FWD",
  "transmission": "Manual-6 Gears",
  "emission_standard": "Es 6",
  "length": "4440",
  "width": "1729",
  "height": "1475",
  "wheelbase": "2600",
  "ground_clearance": "165",
  "doors": "4",
  "seating_capacity": "5",
  "number_of_seating": "2",
  "Bootspace": "480",
  "feul_tank_capacity": "45",
  "front_suspension": "McPherson Struct with Coil Spriing",
  "rear_suspension": "Couple Torsion Beam Axle",
  "front_break_type": "Disc",
  "rear_break_type": "Drum",
  "minimum_turning_Radius": "5.2",
  "stearing_type": "Power assisted",
  "wheels": "Steel Rims",
  "sparewheel": "Steel",
  "front_tyres": "185/65 R15",
  "rear_tyres": "185/65 R15"
  }
]